# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    Firebase-Install-and-Build:
        docker:
            #https://circleci.com/docs/2.0/circleci-images/
            - image: circleci/node:7.10
            - image: circleci/ruby:2.4

        steps:
            - checkout
            - run:
                name: Install bundle
                command: gem install bundler --version=1.17.1
            - run:
                name: Install rubygems
                command: cd blog && bundle install
            - run:
                name: Build Jekyll
                command: cd blog && bundle exec jekyll build --verbose
            - run:
                name: Install Firebase tools if not installed
                command: npm install --save-dev firebase-tools@4.2.1
            - run:
                name: Deploy to Firebase
                command: ln -s ./node_modules/.bin/firebase . && ./firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
    version: 2
    Example_Workflow:
        jobs:
            - Firebase-Install-and-Build
