title: Ashwin's Blog
email: ashwin67@gmail.com
simple_search: http://google.com/search
description: >- # this means to ignore newlines until "baseurl:"
  42
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ashwinupadhyaya.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ashwin67
github_username:  ashwin67

# Build settings
markdown: kramdown
kramdown:
   input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#theme: jekyll-athena
#plugins:
#  - jekyll-feed

#permalink: /articles/:short_year/:title
#timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
#editor: gvim
#git:
#  branch: master
#transfer:
#  command: rsync
#  settings: -av
#  source: _site/
#  destination: ~/Git/clayh53.github.com/
